### ISSUE TITLE
Content not properly centered anymore

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#28]
I'm feeling like there are way too many wrappers. I understand why we need container, row, and column. But why another div inside the header? 

Things are also feeling pretty broken without being in the container in the middle:
![screen shot 2016-05-13 at 4 24 13 pm](https://cloud.githubusercontent.com/assets/397895/15262311/1d3aedc4-1927-11e6-9127-c2e976e860d8.png)

**Comment by biolithic** [comment]
This is a tough one as @wesruv put it in there and I believe he is away for
the weekend.

I think <section class="l-wrapper-inner"> is in there so that we can center
stuff inside of <main class="l-wrapper"> but since there is nothing really
between main and .layout, maybe that's what can be the centering thing?

And take out the l-wrapper-inner?

Just some quick thoughts

**Comment by jenlampton** [comment]
Instead of fixing this problem I think I'm leaning toward going back the other way, closing this issue in favor of https://github.com/biolithic/backdroplayouts/issues/30
