### ISSUE TITLE
restore use of divs for wrapper main and section

### ISSUE THREAD

**Issue by jenlampton** [biolithic/backdroplayouts#29]
I noticed in a recent commit that @wesruv added new main and section tags, but I don't think these are in use correctly. Now, I am NOT a html5 expert, but I don't think we should be using more than one main tag on a page, for example.

Many people have differing opinions on how and when HTML5 tags should be used. I think that for core it would be wiser to stick to the tried and true - DIVs - wherever opinions may differ.  If people want more mains and sections they can override the template and change them.  If opinions start to converge in the future, we can change core then.

**Comment by jenlampton** [comment]
I restored the divs for main and section.

**Comment by wesruv** [comment]
@jenlampton is correct that we only want one `<main>` per page. My thought there was `<main>` should cover everything that isn't the site header/footer. It might need to be an extra wrapper in some instances to make that work.

Not having a `<main>` or a wrapper with `aria-role="main"` is an accessibility issue, if that's still gone it needs to go back in.

`<section>` is mostly semantically meaningless, it's a step up from `<div>` in that all it adds is that it wraps something somewhat important, but not cool enough to be `<header>`, `<article>`, `<main>`, `<aside>`, etc etc.

For any disagreement about how to use HTML tags, I'd say MDN and HTML5Doctor should be used as gospel :smile: (in lieu of the spec since it tends to be indecipherable academic nonsense to me)

**Comment by biolithic** [comment]
@wesruv -- I think the proper place for this conversation is either core or
https://github.com/backdrop-contrib/b4_radix_full , not in a feature
branch/sandbox of code which has been merged into core since.  I appreciate
it, but filing issues against a dev branch of reference module on Mike's
repo may be superceded by the existence of the official
https://github.com/backdrop-contrib/reference , which is like this issue.
Thanks!

For reference comparing the two layout approaches:
Extra markup layouts mainly done by Wesruv
https://github.com/backdrop-contrib/b4_radix_full/blob/master/geary_full/layout--geary-full.tpl.php
line 80:
<main class="col-md-12 l-content" role="main" aria-label="Main Content">

Core layouts using no main tag:
https://github.com/backdrop/backdrop/blob/1.x/core/layouts/geary/layout--geary.tpl.php
line 74:

<div class="l-thirds-region col-md-4">[etc]</div>

**Comment by wesruv** [comment]
It took me a while to figure out that I was commenting in your repo this morning :stuck_out_tongue: 

I made https://github.com/backdrop/backdrop-issues/issues/1970 though, with some updates after some research
